version: "3.9"
services:
  redis-alpine:
    container_name: redis_alpine
    image: "redis:7.2.4-alpine"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redisdata:/data
    environment:
      - REDIS_ARGS=--appendonly yes --save ""
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
